### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by mvdgun** [maurosoft1973/FileSystem#1]
Hello,

I've noticed that you've duplicated my project in your repository, which is perfectly acceptable under the MIT license. However, I'd like to remind you of a specific requirement from the license:

"The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software."

This means that you are obligated to include the original copyright notice in your copyright file. You can find the copyright notice in the original repository here: [SharpGrip FileSystem](https://github.com/SharpGrip/FileSystem/blob/master/LICENSE).

Thank you for your understanding and cooperation.

**Comment by maurosoft1973** [comment]
Hello,

i have changed the license file, now it should be correct.
